name: deploy from main

on:
  push:
    branches: [ main ]

env:
  SHARP_INSTALL_FORCE: true
  APP_BASE_PATH: hushlink/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Install global deps (workbox-cli)
      run: yarn global add workbox-cli
    - name: Build app
      run: make build
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist